name: Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Execute pre-commit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run pre-commit
        uses: pre-commit-ci/lite-action@v1.0.0
