name: Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tarpaulin:
    name: Generate code coverage

    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --out Xml --all-features --benches --tests --examples --workspace

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
